language: nix

script:
  - nix-build -Q --argstr channel $CHANNEL

git:
  depth: 1
sudo: false
os:
  - linux
  - osx

env:
  - CHANNEL=nixos-unstable
  - CHANNEL=nixpkgs-unstable

cache:
  directories:
    - /nix/store

notifications:
  email: false
