language: nix

script:
  - nix-build -Q --argstr channel $CHANNEL

git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: trusty
      env: CHANNEL=nixos-unstable
    - os: linux
      dist: trusty
      env: CHANNEL=nixos-18.09
    - os: osx
      env: CHANNEL=nixpkgs-unstable
    - os: osx
      env: CHANNEL=nixpkgs-18.09-darwin

cache:
  directories:
    - /nix/store

notifications:
  email: false
