language: nix

script:
  - nix-build -Q --argstr nixpkgs-url $NIXPKGS

git:
  depth: 1
sudo: false
os:
  - linux
  - osx

env:
  - NIXPKGS=nixos.org/channels/nixos-unstable/nixexprs.tar.xz
  - NIXPKGS=nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz
  - NIXPKGS=nixos.org/channels/nixos-18.03/nixexprs.tar.xz
  - NIXPKGS=nixos.org/channels/nixpkgs-18.03-darwin/nixexprs.tar.xz

cache:
  directories:
    - /nix/store

notifications:
  email: false
