name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Nix install
      run: |
        curl https://nixos.org/nix/install | sh
        source $HOME/.nix-profile/etc/nix.sh
    - name: Build
      run: nix-build
